# Generated by Django 5.1.6 on 2025-02-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lt_july_01_final_data_12_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('milestone', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('time_stamp', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('box_coordinates', models.TextField(blank=True, null=True)),
                ('processing_time', models.CharField(blank=True, max_length=255, null=True)),
                ('x1', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('y1', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('w', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('h', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cx', models.IntegerField(blank=True, null=True)),
                ('cy', models.IntegerField(blank=True, null=True)),
                ('eucl', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('idle', models.CharField(blank=True, max_length=255, null=True)),
                ('group_talking', models.CharField(blank=True, max_length=255, null=True)),
                ('no_helmet', models.CharField(blank=True, max_length=255, null=True)),
                ('idle_count', models.IntegerField(blank=True, null=True)),
                ('group_count', models.IntegerField(blank=True, null=True)),
                ('no_helmet_count', models.IntegerField(blank=True, null=True)),
                ('no_vest_count', models.IntegerField(blank=True, null=True)),
                ('no_vest', models.CharField(blank=True, max_length=255, null=True)),
                ('duplicate', models.BooleanField(blank=True, default=False, null=True)),
                ('track_id', models.IntegerField(blank=True, null=True)),
                ('group_event', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'public.app_lt_july_01_final_data_12_hours',
            },
        ),
    ]
